# Generated by Django 4.2.6 on 2024-01-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmchoice',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
