# Generated by Django 4.2.6 on 2024-01-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_filmchoice_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmchoice',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
