# Generated by Django 4.2.13 on 2024-05-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_watchedfilm_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedfilm',
            name='poster_url',
            field=models.URLField(),
        ),
    ]
