# Generated by Django 4.2.13 on 2024-06-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_watchedfilm_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
