# Generated by Django 4.2.13 on 2024-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_film_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='kp_rate',
            field=models.CharField(db_index=True, max_length=10, null=True, verbose_name='Рэйтинг'),
        ),
    ]
