# Generated by Django 4.2.13 on 2024-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_film_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Год'),
        ),
    ]
